// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnzhyizklbflkikymzff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuemh5aXprbGJmbGtpa3ltemZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDc2NzIsImV4cCI6MjA2Mjc4MzY3Mn0.IwVanQByxxa15zkQNGAq9W0gTEH-inrYsfzrt-_HXuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);